### ISSUE TITLE
Feature Request: Hotkey / Keyboard Shortcut

### ISSUE THREAD

**Issue by SenorFusion** [Osndok/zim-plugin-nowbutton#1]
First - Thanks so much for making this plugin (and your other one). They are both extremely helpful and I'm really excited to see the Zim ecosystem growing! It's such an under appreciated app.

Small feature request: Can you include a hotkey / keyboard shortcut for the nowbutton ?

Thanks!

**Comment by Osndok** [comment]
I'd be happy to... and thanks for the kind words, it's really nice to know that someone else is helped by and appreciates my little bits of code.

I agree with you sentiment regarding Zim. Even as imperfect an incomplete as it may be (from my ideal), it has totally revolutionized how I use my computer and is slowly becoming an organizing force in my life at-large.

When I first imagined the 'now button', I thought it would be good to have an OS-level keyboard shortcut for it... so that no matter where you are or what you are doing one could make a quick log entry (or, for example, note the time a phone call starts with the press of a button). This would be accomplished by calling the plugin with a "zim plugin nowbutton" command. I never quite got around to doing this.

It _would_ be much easier to make a zim-level keyboard shortcut, which (I think) is what you are asking for.

Since you would be the primary user of this hot key, it seems only fitting that you might help choose it's binding. Do you have a preference? I know that Ctrl+L & Ctrl+N are already taken... perhaps one of the later f-keys (F9, F10, F11, F12)?

**Comment by Osndok** [comment]
I haven't heard back from you, so I've added the shortcut "Ctrl-Shift-E" (for... "entry"), and there is also now a "entries shortly after midnight go on the same page" feature that is tweakable in-source. Hope that helps!

**Comment by SenorFusion** [comment]
Hey @Osndok 

Sorry for the slow reply here, I was away from my computer this weekend. 

Thanks a ton for the fast turnaround on this! I tested the hotkey and it works great. I think Ctrl+Shift+E is a fine choice. 

> When I first imagined the 'now button', I thought it would be good to have an OS-level keyboard shortcut for it... so that no matter where you are or what you are doing one could make a quick log entry (or, for example, note the time a phone call starts with the press of a button). This would be accomplished by calling the plugin with a "zim plugin nowbutton" command. I never quite got around to doing this.

I have a couple of workarounds for this currently in place that you might like. 

Keyboard shortcut to Start Zim (if it's not) and automatically bring it to front window and desktop:

`bash -c "zim && wmctrl -R \"Notes - Zim\" "`

Source: https://www.drostan.org/2011/01/hacking-away-my-zim-notebook/

I also have an anywhere-any-time-quickly-jot-something-down-shortcut with:

`zim --plugin quicknote notebook=Commonplace namespace=:Clippings input=stdin encoding=url`

using the default Zim Quicknote plugin: http://zim-wiki.org/manual/Plugins/Quick_Note.html

Both of the above are mapped as keyboard shortcuts in my desktop hotkey settings. Neither of those integrates with your nowbuton plugin but it might give you some ideas for how to do it or some code to appropriate for the now button.

Thanks again!
